name: Build Atomix APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Android APK
      uses: gradle/gradle-build-action@v2
      with:
        arguments: app:assembleDebug

    - name: Upload APK File
      uses: actions/upload-artifact@v4
      with:
        name: Atomix-App-APK
        path: app/build/outputs/apk/debug/app-debug.apk
